#!/usr/bin/env python2

import os
import sys

# Variables configured at build time.
llvm_lit_root = os.path.join(os.path.dirname(__file__), "llvm-lit")

# Make sure we can find the lit package.
sys.path.insert(0, llvm_lit_root)

builtin_parameters = {}

if __name__=='__main__':
    from lit.main import main
    main(builtin_parameters)